ALTER TABLE fornecedores 
ADD COLUMN inscricao_estadual VARCHAR(50),
ADD COLUMN telefone VARCHAR(20),
ADD COLUMN email VARCHAR(100),
ADD COLUMN cep VARCHAR(10),
ADD COLUMN endereco VARCHAR(255),
ADD COLUMN numero VARCHAR(20),
ADD COLUMN complemento VARCHAR(100),
ADD COLUMN bairro VARCHAR(100),
ADD COLUMN cidade VARCHAR(100),
ADD COLUMN uf VARCHAR(2);
